### ISSUE TITLE
Unexplained timeouts on indexer-service and indexer-agent

### ISSUE THREAD

**Issue by alexandruast** [graphprotocol/indexer#161] opened 2020-12-19 14:08 UTC
indexer-service and indexer-agent are spamming these messages which more or less look the same:
 ```
 {"level":40,"time":1608385891593,"pid":1,"hostname":"bbbee3684e0b","name":"IndexerAgent","err":{"type":"IndexerError","message":"Unhandled promise rejection","stack":"IndexerError: Unhandled promise rejection\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:97:12)\n    at process.<anonymous> (/opt/indexer/packages/indexer-agent/dist/commands/start.js:212:39)\n    at process.emit (events.js:321:20)\n    at process.EventEmitter.emit (domain.js:482:12)\n    at processPromiseRejections (internal/process/promises.js:209:33)\n    at processTicksAndRejections (internal/process/task_queues.js:98:32)","code":"IE035","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie035","cause":{"type":"Error","message":"timeout (requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":105,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", timeout=120000, url=\"http://eth-mainnet.stakesystems.io/\", code=TIMEOUT, version=web/5.0.11)","stack":"Error: timeout (requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":105,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", timeout=120000, url=\"http://eth-mainnet.stakesystems.io/\", code=TIMEOUT, version=web/5.0.11)\n    at Logger.makeError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:179:21)\n    at Timeout._onTimeout (/opt/indexer/node_modules/@ethersproject/web/lib/index.js:148:35)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)","reason":"timeout","code":"TIMEOUT","requestBody":"{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":105,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","timeout":120000,"url":"http://eth-mainnet.stakesystems.io/"}},"msg":"Unhandled promise rejection"}
 ```
 This is across infura, alchemy and two own nodes.

**Comment by Jannis** [comment] 2021-01-06 15:50
Duplicate of #183.

**Closed by Jannis** 2021-01-06 15:50 UTC
