### ISSUE TITLE
`npm` install failed.

### ISSUE THREAD

**Issue by 99Kies** [graphprotocol/indexer#543] opened 2022-11-17 01:12 UTC
command:

```bash
sudo npm install -g @graphprotocol/indexer-service
```

npm log:

```
npm ERR! path /usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/cost-model
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build=false --update-binary || yarn build-release
npm ERR! response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! yarn run v1.22.19
npm ERR! $ yarn build --release
npm ERR! $ cargo-cp-artifact -a cdylib node_plugin ./native/index.node -- cargo build --message-format=json-render-diagnostics --release
npm ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.12.1 | linux | x64
npm ERR! node-pre-gyp http GET https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Linux 5.15.0-1019-aws
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/cost-model
npm ERR! node-pre-gyp ERR! node -v v18.12.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok
npm ERR! Error: could not find the `cargo` executable.
npm ERR!
npm ERR! You can find instructions for installing Rust and Cargo at:
npm ERR!
npm ERR!     https://www.rust-lang.org/tools/install
npm ERR!
npm ERR!
npm ERR! Did not copy "cdylib:node_plugin"
npm ERR! error Command failed with exit code 1.
npm ERR! error Command failed with exit code 1.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-17T01_10_00_296Z-debug-0.log
```

**Comment by 99Kies** [comment] 2022-11-17 01:14
![image](https://user-images.githubusercontent.com/45918704/202329774-ba911458-2e08-4d33-83cc-c46efdeaabf7.png)
![image](https://user-images.githubusercontent.com/45918704/202329850-1c350340-9393-4116-908f-6b3d07e25046.png)

**Comment by neysofu** [comment] 2022-12-14 12:02
Same here, even though in my case it's reaching for a different link: `https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v111-linux-x64.tar.gz`.

**Comment by neysofu** [comment] 2022-12-14 12:19
Closing as duplicate of https://github.com/graphprotocol/indexer/issues/489. Installing Node.js 16.17.1 seems to fix the issue.

**Closed by neysofu** 2022-12-14 12:19 UTC
Labels: duplicate
