### ISSUE TITLE
Error: yarn fails to install dependencies for Sub-Graph Studio

### ISSUE THREAD

**Issue by DorianDaSilva** [graphprotocol/indexer#540] opened 2022-11-10 15:00 UTC
```
Error: Command failed: yarn
```
================================================================================

![image](https://user-images.githubusercontent.com/80294826/200617922-6d1b7bf3-65f7-4819-ac4e-e22c412547ce.png)

================================================================================

I follow the steps below to set up a ```sub-graph``` in ```graph studio``` but install fails when yarn is installing dependencies.

1-```yarn global add @graphprotocol/graph-cli```

2-```graph init --studio nft-marketplace``` - This is were the error is prompted on the final step (yarn dependencies)

I do see the files and folders in VsCode but due to error with yarn I assume install is incomplete (img below)
![image](https://user-images.githubusercontent.com/80294826/201126592-f57ad5ae-7116-485d-9fe3-3ced661ec4ab.png)

====================================================================================

**Package.json**

```
{
  "name": "nft-marketplace",
  "license": "UNLICENSED",
  "scripts": {
    "codegen": "graph codegen",
    "build": "graph build",
    "deploy": "graph deploy --node https://api.studio.thegraph.com/deploy/ nft-marketplace",
    "create-local": "graph create --node http://localhost:8020/ nft-marketplace",
    "remove-local": "graph remove --node http://localhost:8020/ nft-marketplace",
    "deploy-local": "graph deploy --node http://localhost:8020/ --ipfs http://localhost:5001 nft-marketplace",
    "test": "graph test"
  },
  "dependencies": {
    "@graphprotocol/graph-cli": "0.35.0",
    "@graphprotocol/graph-ts": "0.28.1"
  },
  "devDependencies": { "matchstick-as": "0.5.0" }
}

```

====================================================================================

**Yarn-error.log**

```
......

Yarn version: 
  1.22.19

Node version: 
  16.14.2

Platform: 
  linux x64

Trace: 
  SyntaxError: /home/<name>/.cache/yarn/v6/npm-binaryen-102.0.0-nightly.20211028-8f1efb0920afd34509e342e37f84313ec936afb2-integrity/node_modules/binaryen/.yarn-metadata.json: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at /home/<name>/.yarn/lib/cli.js:1629:59
      at Generator.next (<anonymous>)
      at step (/home/<name>/.yarn/lib/cli.js:310:30)
      at /home/<name>/.yarn/lib/cli.js:321:13

npm manifest: 
  {
    "name": "nft-marketplace",
    "license": "UNLICENSED",
    "scripts": {
      "codegen": "graph codegen",
      "build": "graph build",
      "deploy": "graph deploy --node https://api.studio.thegraph.com/deploy/ nft-marketplace",
      "create-local": "graph create --node http://localhost:8020/ nft-marketplace",
      "remove-local": "graph remove --node http://localhost:8020/ nft-marketplace",
      "deploy-local": "graph deploy --node http://localhost:8020/ --ipfs http://localhost:5001 nft-marketplace",
      "test": "graph test"
    },
    "dependencies": {
      "@graphprotocol/graph-cli": "0.35.0",
      "@graphprotocol/graph-ts": "0.28.1"
    },
    "devDependencies": { "matchstick-as": "0.5.0" }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```

====================================================================================

Can you please help me figure out a way around this issue, please? Thank you!

**Comment by fordN** [comment] 2022-11-11 19:55
Hey @DorianDaSilva 👋 

Were you able to get past this issue? It looks like yarn/npm had trouble parsing a JSON object when it was trying to build dependencies for you project, so likely there was a malformed or unsupported object in your package.json or in a file in one of the dependencies. 

For the future please direct graph-cli issues to the [the graph-cli repo](https://github.com/graphprotocol/graph-cli) or to the #subgraph-development channel in [The Graph discord](https://github.com/graphprotocol).

**Comment by fordN** [comment] 2022-11-11 19:56
I'm going to close this issue here. If you would like to flag the issue to the graph-cli development team and continue to root cause I'd suggest making a new issue in [the graph-cli repo](https://github.com/graphprotocol/graph-cli).

**Closed by fordN** 2022-11-11 19:56 UTC
