### ISSUE TITLE
Memory and CPU leak in agent and service

### ISSUE THREAD

**Issue by chriswessels** [graphprotocol/indexer#41] opened 2020-09-01 21:30 UTC
Hey there,

I'd been running release `sha-54d4905` on Kubernetes for a few days before upgrading to a new release, and noticed a huge drop in memory usage for the `indexer-agent` and `indexer-serivce`.

Looking back at memory usage for the deployments:

![Screenshot 2020-09-01 at 22 23 40](https://user-images.githubusercontent.com/2657600/91907901-98c31400-eca2-11ea-8400-35f33357a27c.png)

![Screenshot 2020-09-01 at 22 25 40](https://user-images.githubusercontent.com/2657600/91907904-9a8cd780-eca2-11ea-87b8-a961597fd43e.png)

Both seem to have a fairly consistent and linear growth in memory usage of time.

Let me know if there are any further details I can provide!

Chris

**Comment by aasseman** [comment] 2022-05-19 03:41
I'm also observing this issue on v0.18.6. However I've found a good way to accelerate it: send lots of GraphQL queries to the `indexer-agent` management endpoint.

However I am not sure if certain types of queries are worse than others. Read below.

*Context*
As @fordN and @chriswessels already know, I'm currently running experiments that require constantly updating the Agora models. In this particular case, I am updating the model variables for each subgraph every 3 minutes.
In the plot below, every drop is the OOM killer killing the `indexer-agent`. The frequency increased around May 10th, when I deployed my experiment to the indexer.
![image](https://user-images.githubusercontent.com/33075224/169199119-d01b2e92-8839-4441-94f5-76dc8392eff2.png)

**Comment by aasseman** [comment] 2022-05-20 18:23
Update: The problem is still present on v0.19.2.

**Comment by kaiwetlesen** [comment] 2022-09-21 17:45
Update: immediately preceding the OOM crash, queries begin failing. This causes a drop in quality of service.
![out-of-memory-crash-grafana](https://user-images.githubusercontent.com/9599381/191574686-adf74c3d-403b-4eb9-b882-8fcf3cfb5c1e.png)
![indexer-service-memory-leak](https://user-images.githubusercontent.com/9599381/191574711-3a161a5f-9a60-4e7b-a67e-3eecbdbb0bb2.png)

**Comment by aasseman** [comment] 2023-03-01 00:21
Update: the problem is still present on v0.20.12

**Comment by alex-pakalniskis** [comment] 2024-03-14 17:17
Figment appears to be experiencing this issue too (shared with me on March 14, 2024)

**Comment by fordN** [comment] 2024-11-13 17:57
Recent changes to indexer-agen t have improved memory usage significantly. At E&N we are no longer seeing the runaway memory usage. Closing this issue for now.

**Closed by fordN** 2024-11-13 17:57 UTC
Labels: bug
