### ISSUE TITLE
Why this error

### ISSUE THREAD

**Issue by ordifind** [graphprotocol/indexer#433] opened 2022-07-02 09:26 UTC
Subgraph failed with non-deterministic error: failed to process trigger: block #19194303 (0x6f6c…443c), transaction cf85d788f16e4827fa9c7248bce8a89e7f9882c307d55da11904dd6e6fe7d06e: `allocate` function not found, retry_delay_s: 240, attempt: 1

**Comment by fordN** [comment] 2022-07-12 19:23
Hey @sameerneupane this appears to be an issue with the subgraph itself.

Could you share the subgraph deployment ID?

**Comment by samirneupane62** [comment] 2022-07-13 01:17
the issue is solved ,, But why the subgrah is syncing very slowly

**Comment by fordN** [comment] 2022-08-04 18:18
@samirneupane62 I'd suggest popping into [the discord](https://github.com/graphprotocol) #subgraph-development channel to discuss ways to speed up your subgraph.  

Or if you would like to provide details here I can point you to documentation or provide suggestions, but the feedback loop will be slower here.

**Comment by fordN** [comment] 2024-07-12 19:22
Closing this issue as it's old.

**Closed by fordN** 2024-07-12 19:22 UTC
Labels: question
